services:
  backend:
    image: ghcr.io/slowlydev/f1-dash-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 4000:4000  # Live Service
      - 4001:4001  # API Service
      - 4002:4002  # Analytics Service
    environment:
      - ORIGIN=http://localhost:3000
      - LIVE_ADDRESS=0.0.0.0
      - LIVE_PORT=4000
      - API_ADDRESS=0.0.0.0
      - API_PORT=4001
      - ANALYTICS_ADDRESS=0.0.0.0
      - ANALYTICS_PORT=4002
      - LOG_LEVEL=debug
      - F1_SIGNALR_URL=https://livetiming.formula1.com/signalr
      - F1_ICAL_URL=https://ics.ecal.com/ecal-sub/660897ca63f9ca0008bcbea6/Formula%201.ics
      - SCHEDULE_CACHE_TTL=1800
      - DATABASE_URL=postgres://postgres:password@timescaledb:5432/postgres
    depends_on:
      - timescaledb

  frontend:
    image: ghcr.io/slowlydev/f1-dash:latest
    build:
      context: ./dash/
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_LIVE_URL=http://localhost:4000
      - API_URL=http://backend:4001
      - DISABLE_IFRAME=1

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - timescale-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  timescale-data:
